apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-affinity
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - gp
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80

# Node Anti-Affinity is generally implemented using the operators:
# NotIn
# DoesNotExist

  # Each node is scored based on how many preferences it matches and their associated weights.

# Node	disktype=ssd (weight: 5)	zone=us-east (weight: 3)	Total Score
# node-a	✅ (5)	✅ (3)	8
# node-b	❌ (0)	✅ (3)	3
# node-c	✅ (5)	❌ (0)	5