# Here are the three taint effects in Kubernetes:
# NoSchedule – Pod will not be scheduled on the node unless it tolerates the taint.
# PreferNoSchedule – Kubernetes tries to avoid scheduling the pod on the node, but it's not guaranteed.
# NoExecute –
# New pods won't be scheduled and
# Existing pods will be evicted unless they tolerate the taint.
# command to untaint: kubectl taint nodes gke-cluster-1-default-pool-64ecaeb7-5jsm type-

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      tolerations:
        - key: "type"
          operator: "Equal"
          value: "highcpu"
          effect: "NoSchedule"
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
