apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy-task-backend
  name: deploy-task-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-backend
  strategy: {}
  template:
    metadata:
      labels:
        app: task-backend
    spec:
      serviceAccountName: gke-sql
      containers:
      - image: bhabanisn/task-backendmysql
        name: task-backend-con
        env :
         - name: spring.datasource.url
           valueFrom:
            configMapKeyRef:
              key: datasourceurl
              name: gke
         - name: spring.datasource.username
           valueFrom:
            configMapKeyRef:
              key: dbusername
              name: gke
         - name: spring.datasource.password
           valueFrom:
            secretKeyRef:
              key: db-password
              name: db-password
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
      - name: cloudsql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0
        args:
          - "--private-ip"
          - "single-archive-466109-a1:us-central1:gke-sql"
        securityContext:
          runAsNonRoot: true