apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: task-frontend
  name: task-frontend-lb-svc
  annotations:
    networking.gke.io/load-balancer-type: "External"
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: task-frontend
  type: LoadBalancer
  #loadBalancerIP: 34.42.213.128 - create staiic ip and mention here. otherwise gcp will create ip address.
status:
  loadBalancer: {}
