apiVersion: v1
kind: Service
metadata:
  labels:
    app: svc-task-backend
  name: task-backend-clusterip-svc
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: task-backend
  type: ClusterIP
