apiVersion: v1
kind: ResourceQuota
metadata:
  name: full-quota
  namespace: default
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 4Gi
    pods: "2"

# if you define requests.cpu (or any specific compute resource like requests.memory, limits.cpu, etc.) in a ResourceQuota for a namespace, then every Pod (or container) created in that namespace must specify the corresponding resource request in its YAML. Otherwise Apiserver rejects it.
    