apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-demo-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: vpa-demo
  updatePolicy:
    updateMode: "Auto"


# Off mode. you can see below recommendation
  # Recommendation:
  #   Container Recommendations:
  #     Container Name:  nginx
  #     Lower Bound:
  #       Cpu:     1m
  #       Memory:  3145728
  #     Target:
  #       Cpu:     1m
  #       Memory:  4194304
  #     Uncapped Target:
  #       Cpu:     1m
  #       Memory:  4194304
  #     Upper Bound:
  #       Cpu:     210m
  #       Memory:  769654784
