apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-reader
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]

# you can define cluster role and can use rolebinding with cluster role ref. so no need to duplicate the resource. but any role binding can be namespace scoped
