apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v1
  template:
    metadata:
      labels:
        app: v1
    spec:
      containers:
      - name: container-v1
        image: us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0
        ports:
          - containerPort: 8080
            name: http
        readinessProbe:  # this is to create custom health check
          httpGet:
            path: /v1
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3
        
