#apiVersion: networking.gke.io/v1beta1
#kind: FrontendConfig
#metadata:
#  name: https-redirect-config
# spec:
#   redirectToHttps:
#     enabled: true
#     responseCodeName: MOVED_PERMANENTLY_DEFAULT # (optional, defaults to 301)
