# https://cloud.google.com/kubernetes-engine/docs/how-to/capacity-provisioning#use-job
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capacity-res-deploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: reservation
  template:
    metadata:
      labels:
        app: reservation
    spec:
      priorityClassName: low-priority
      terminationGracePeriodSeconds: 0
      containers:
      - name: ubuntu
        image: ubuntu
        command: ["sleep"]
        args: ["infinity"]
        resources:
          requests:
            cpu: 500m
            memory: 500Mi

# Feature	Job (Single-use) 🚦	Deployment (Consistent) 🔄
# Placeholder lifespan	Ends after completion/eviction	Always recreated
# Capacity available	Only during Job window	Always (persistent overhead)
# Best use case	Short bursts, known time	Continuous buffer for unpredictable workloads
# After workload later	May wait for new nodes	Immediate scheduling